#!/usr/bin/env bash

set -e

CONFIG="install.conf.yaml"
DOTBOT_DIR="dotbot"

DOTBOT_BIN="bin/dotbot"
BASEDIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

cd "${BASEDIR}"
git -C "${DOTBOT_DIR}" submodule sync --quiet --recursive
git submodule update --init --recursive "${DOTBOT_DIR}"

"${BASEDIR}/${DOTBOT_DIR}/${DOTBOT_BIN}" -d "${BASEDIR}" -c "${CONFIG}" --plugin-dir "${BASEDIR}/dotbot-paru" "${@}"

while true
do
      read -r -p "Do you want to install all packages from needed.list? [Y/n] " input
 
      case $input in
            [yY][eE][sS]|[yY])
                  echo Installing!
		  paru -Syu --needed --noconfirm - < ${BASEDIR}/needed.list
                  break
                  ;;
            [nN][oO]|[nN])
                  echo "Okay!"
                  break
                  ;;
            *)
                  echo "Invalid input..."
                  ;;
      esac      
done

while true
do
      read -r -p "Do you want to install all packages from packages.list? [Y/n] " input
 
      case $input in
            [yY][eE][sS]|[yY])
                  echo Installing!
                  paru -Syu --needed --noconfirm - < ${BASEDIR}/packages.list
                  break
                  ;;
            [nN][oO]|[nN])
                  echo "Okay!"
                  break
                  ;;
            *)
                  echo "Invalid input..."
                  ;;
      esac
done
