#!/usr/bin/env bash

set -e

CONFIG="install.conf.yaml"
DOTBOT_DIR="dotbot"

DOTBOT_BIN="bin/dotbot"
BASEDIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

cd "${BASEDIR}"
git -C "${DOTBOT_DIR}" submodule sync --quiet --recursive
git submodule update --init --recursive "${DOTBOT_DIR}"

"${BASEDIR}/${DOTBOT_DIR}/${DOTBOT_BIN}" -d "${BASEDIR}" -c "${CONFIG}" "${@}"

echo "Installing all packages from needed.list"
echo "Press Ctrl+C if you want to skip installing packages."
echo 5.
sleep 1
echo 4.
sleep 1
echo 3.
sleep 1
echo 2.
sleep 1
echo 1.
sleep 1
echo Installing!
paru -Syu --needed --noconfirm - < ${BASEDIR}/needed.list
