theme = "gruvbox-dark"
icons = "material-nf"


[[block]]
block = "focused_window"
max_width = 50
show_marks = "visible"
[block.theme_overrides]
idle_bg = "#282828"
idle_fg = "#dfbf8e"

[[block]]
block = "weather"
format = "{weather_verbose} {temp}"
service = { name = "openweathermap", api_key = "24e8f05e46f42d367e05181472312479", city_id = "2636663", units = "metric" }
[block.theme_overrides]
idle_bg = "#dfbf8e"
idle_fg = "#282828"

[[block]]
block = "memory"
display_type = "memory"
format_mem = "{mem_used}"
clickable = false
[block.theme_overrides]
idle_bg = "#282828"
idle_fg = "#dfbf8e"

[[block]]
block = "cpu"
interval = 1
[block.theme_overrides]
idle_bg = "#dfbf8e"
idle_fg = "#282828"

[[block]]
block = "custom"
command = "uname -r"
interval = "once"
[block.theme_overrides]
idle_bg = "#282828"
idle_fg = "#dfbf8e"

[[block]]
block = "custom"
command = "i3-volume output \"%i %v\n\""
on_click = "i3-volume mute"
signal = 10
[block.theme_overrides]
idle_bg = "#dfbf8e"
idle_fg = "#282828"

[[block]]
block = "time"
interval = 1
format = "%a %d/%m %T"
[block.theme_overrides]
idle_bg = "#282828"
idle_fg = "#dfbf8e"

[[block]]
block = "music"
player = "spotify"
buttons = ["play", "next"]
dynamic_width = true
hide_when_empty = true
max_width = 30
[block.theme_overrides]
idle_bg = "#dfbf8e"
idle_fg = "#282828"
