#! /bin/sh


pgrep -x sxhkd > /dev/null || sxhkd & 

imwheel -k -b 45 &
nitrogen --restore &
picom -b --experimental-backends &
for id in $(xinput list | grep "pointer" | cut -d '=' -f 2 | cut -f 1); do xinput --set-prop $id 'libinput Accel Profile Enabled' 0, 1; done &
$HOME/.config/polybar/launch.sh &
xset r rate 275 45 &

alias bc='bspc config'
alias br='bspc rule'

bc monitor DP-4 -d 1 3 5 7 9
bc monitor DP-2 -d 2 4 6 8 10

bc config border_width        	3
bc config window_gap          	9
bc config border_radius 		6
bc config normal_border_color		\#1E1E2E
bc config focused_border_color	\#575268
bc config presel_feedback_color	\#89DCEB

bc config split_ratio          0.52
bc config borderless_monocle   true
bc config gapless_monocle      false

#br -a Gimp desktop='^8' state=floating follow=on
#br -a Chromium desktop='^2'
#br -a mplayer2 state=floating
#br -a Kupfer.py focus=on
#br -a Screenkey manage=off

[ "$1" = 0 ] && {
	/opt/discord-canary --start-minimized --ignore-gpu-blocklist --disable-features=UseOzonePlatform --enable-features=VaapiVideoDecoder --use-gl=desktop --enable-gpu-rasterization --enable-zero-copy &
	/usr/lib/mate-polkit/polkit-mate-authentication-agent-1 &
	$HOME/.scripts/xidlehook.sh &
	/usr/bin/openrgb --startminimized --profile "blue" &
}
