#! /bin/sh
pgrep -x sxhkd > /dev/null || sxhkd & 

imwheel -k -b 45 &
nitrogen --restore &
picom -b --experimental-backends &
for id in $(xinput list | grep "pointer" | cut -d '=' -f 2 | cut -f 1); do xinput --set-prop $id 'libinput Accel Profile Enabled' 0, 1; done &
nvidia-settings --load-config-only &
$HOME/.config/polybar/launch.sh &
xset r rate 275 45 &

bspc monitor DP-4 -d 1 3 5 7 9
bspc monitor DP-2 -d 2 4 6 8 10

bspc config border_width        		3
bspc config window_gap          		12
bspc config border_radius 			6
bspc config normal_border_color			"#1E1E2E"
bspc config active_border_color			"#1E1E2E"
bspc config focused_border_color		"#575268"
bspc config presel_feedback_color		"#89DCEB"

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      false

[ "$1" = 0 ] && {
	discord-canary --start-minimized --ignore-gpu-blocklist --disable-features=UseOzonePlatform --enable-features=VaapiVideoDecoder --use-gl=desktop --enable-gpu-rasterization --enable-zero-copy &
	/usr/lib/mate-polkit/polkit-mate-authentication-agent-1 &
	$HOME/.scripts/xidlehook.sh &
	/usr/bin/openrgb --startminimized --profile "blue" &
}
